remote_theme: jekyll-theme-minimal
description: docendo discimus
# Site wide configuration

title: Galileu Kim
logo: /images/minimalism_origami.jpg
# tagline: docendo discimus
date_format: "%b %-d, %Y"
social_links:
  github:  galileukim
  linkedIn: in/galileu-kim # format: locale/username
theme: jekyll-theme-minimal