remote_theme: thelehhman/texture
# Site wide configuration

title: Galileu Kim
description: Personal website (demo)
locale: en_US
logo: minimalism_origami.jpg

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Galileu Kim
  avatar: minimalism_origami.jpg
  bio: "Political economist at Princeton University"
  email: galileuk@princeton.edu
  # twitter: laderast
  linkedin: #username
  github: galileukim