remote_theme: jekyll-theme-minimal
description: docendo discimus.
# Site wide configuration

title: GALILEU KIM
# logo: /images/daily_minimal.jpg
# tagline: docendo discimus
date_format: "%b %-d, %Y"
social_links:
  github:  galileukim
  linkedIn: in/galileu-kim # format: locale/username
theme: jekyll-theme-minimal