remote_theme: thelehhman/texture
# Site wide configuration

texture:
  title: Galileu Kim
  tagline: Data scientist.
  date_format: "%b %-d, %Y"
  style: black

  social_links:
    github:  galileukim
    linkedIn: in/galileu-kim # format: locale/username