remote_theme: thelehhman/texture
# Site wide configuration

title: Galileu Kim
description: Personal website (demo)
locale: en_US
logo: minimalism_origami.jpg

texture:
  title: Galileu Kim
  tagline: Data scientist.
  date_format: "%b %-d, %Y"

  social_links:
    github:  galileukim
    linkedIn: in/galileu-kim # format: locale/username